#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
    paths-ignore:
      - "*/**.md"
      - "*/**.yml"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
#  Temporarily disabled because main is broken
#  duckdb-next-build:
#    name: Build extension binaries (next)
#    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
#    with:
#      duckdb_version: 1.1.2
#      ci_tools_version: 1.1.2
#      extension_name: chsql

  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.2.1
    with:
      duckdb_version: v1.2.1
      ci_tools_version: v1.2.1
      extension_name: chsql
  process-artifacts:
    name: Process Extension Artifacts
    needs: duckdb-stable-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts

      - name: List downloaded artifacts
        run: |
          mkdir to-upload; \
          for l in `ls downloaded-artifacts`; do \
            VER=`echo $l | cut -d '-' -f 2`; \
            ARCH=`echo $l| cut -d '-' -f 4`; \
            EXT=`ls downloaded-artifacts/$l | cut -b 7-`; \
            mv downloaded-artifacts/$l/chsql.$EXT to-upload/chsql.$VER.$ARCH.$EXT; \
          done; \
          ls -la to-upload